### ISSUE TITLE
你好，基础表格这里存在一个问题

### ISSUE THREAD

**Issue by liyibo1110** [Recklesslmz/elementUI#1]
比如我在列表中点了“编辑”，然后修改了比如name字段，这时候我点了“取消”而不是“保存”，这时回到原列表，发现数据也变了（当然这个操作是没有提交给后端保存的，只是显示错了，刷新就会正常）
在这里我是做了业务修改，在开启编辑窗口时，将tableData[index]的对象深拷贝了一份出来（要自己实现，ES6好像都没有深COPY机制），当点击“取消”时，将tableData[index]里面的字段逐一赋值回去（不能直接将tableData[index]直接指向拷贝对象，双向绑定机制应该没有检测到引用改变）

**Comment by Recklesslmz** [comment]
感谢你提出宝贵的意见呀，当初匆匆忙忙写的这个demo有很多不足之处，我仔细想了下你提的问题并且也实际操作了下，确实会有你所描述的问题，若是将对应的数据存入localstorage再取出也是可以的~
