### ISSUE TITLE
"基础表格"编辑问题

### ISSUE THREAD

**Issue by chess99** [Recklesslmz/elementUI#4]
"编辑->确定"操作后, 不更新被编辑的条目本身, 而是产生了一个新条目

**Comment by qwe1qwe1** [comment]
update() {
      this.form.date = reformat(this.form.date)
      this.tableData.push(this.form)
      this.dialogFormVisible = false
    },

**Comment by qwe1qwe1** [comment]
可以在点击编辑的时候记录一下索引，在date里面定义一个空的index。
`handleEdit(index, row) {
      // console.log(index, row)
      this.index = index
    },`
点击确认修改的时候：
`// 确认修改
    onSubmit() {
      this.tableData[this.index] = this.form
}`
