### ISSUE TITLE
table里面可以用select吗？我试过不行啊

### ISSUE THREAD

**Issue by wangjiao1** [Recklesslmz/elementUI#8]
table里面可以用select吗？我试过不行啊
 <el-table-column label="操作人">
                        <el-select v-model="value6" placeholder="请选择">
                            <el-option v-for="item in cities" :key="item.value" :label="item.label" :value="item.value">
                            <span style="float: left">{{ item.label }}</span>
                            <span style="float: right; color: #8492a6; font-size: 13px">{{ item.value }}</span>
                            </el-option>
                        </el-select>
                    </el-table-column>
 <el-select v-model="value6" placeholder="请选择">
                            <el-option v-for="item in cities" :key="item.value" :label="item.label" :value="item.value">
                            <span style="float: left">{{ item.label }}</span>
                            <span style="float: right; color: #8492a6; font-size: 13px">{{ item.value }}</span>
                            </el-option>
                        </el-select>
                    </el-table-column>

**Comment by CN-L** [comment]
百度一下

**Comment by Recklesslmz** [comment]
我已经更新select的使用方法了，请看下更新
